<<<<<<< HEAD
blank_issues_enabled: false
=======
>>>>>>> 3ea0d20e2cf7cf08c7e8e8c098ff725c4ea92224
contact_links:
  - name: 讨论交流 / Communication
    url: https://t.me/clash_verge_rev
    about: 在 Telegram 群组中与其他用户讨论交流 / Communicate with other users in the Telegram group
