name: Updater CI

on: workflow_dispatch
permissions: write-all
<<<<<<< HEAD
env:
  HUSKY: 0

=======
>>>>>>> 3ea0d20e2cf7cf08c7e8e8c098ff725c4ea92224
jobs:
  release-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
<<<<<<< HEAD
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.14.0'

      - uses: pnpm/action-setup@v5
=======
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: pnpm/action-setup@v4
>>>>>>> 3ea0d20e2cf7cf08c7e8e8c098ff725c4ea92224
        name: Install pnpm
        with:
          run_install: false

      - name: Pnpm install
        run: pnpm i

      - name: Release updater file
        run: pnpm updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-update-for-fixed-webview2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
<<<<<<< HEAD
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.14.0'

      - uses: pnpm/action-setup@v5
=======
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: pnpm/action-setup@v4
>>>>>>> 3ea0d20e2cf7cf08c7e8e8c098ff725c4ea92224
        name: Install pnpm
        with:
          run_install: false

      - name: Pnpm install
        run: pnpm i

      - name: Release updater file
        run: pnpm updater-fixed-webview2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
